name: Flutter Pi deb packager
on:
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      # Dependencies
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdrm-dev libgbm-dev ttf-mscorefonts-installer fontconfig libsystemd-dev libinput-dev libudev-dev  libxkbcommon-dev
          version: 1.0
      - run: |
          fc-cache

      # Build
      - uses: actions/checkout@v4
        with:
          repository: "ardera/flutter-pi"
      - run: |
          cd flutter-pi
          mkdir build && cd build
          cmake ..
          make -j`nproc`
      - uses: actions/upload-artifact@v3
        with:
          name: test
          path: flutter-pi
